### ISSUE TITLE
WHOIS cache miss for fubar.com

### ISSUE THREAD

**Issue by sugarfunk** [nwesterhausen/domain-monitor#33]
**Describe the bug**
No matter what domain I enter, I get "WHOIS cache miss for fubar.com". I have tried waiting 24 hours based on a different ticket.
Running via docker
whois data folder set to 777

**To Reproduce**
1. Add a domain
2. Get a error
3. 8/18/2021, 9:31:10 AM: Socket Connection Established
8/18/2021, 9:31:10 AM: Configuration data received.
8/18/2021, 9:31:10 AM: Domain configuration received.
8/18/2021, 9:31:10 AM: WHOIS cache miss for bartdyer.com

**Expected behavior**
Whois to load

**Screenshots**
![image](https://user-images.githubusercontent.com/1361962/129908863-16c4078e-4758-4219-b359-acca263b6ec2.png)

**Comment by nwesterhausen** [comment]
What are the contents of /app/whois-data inside the container?

Can you share the log for the container?

**Comment by sugarfunk** [comment]
Whois is blank
![image](https://user-images.githubusercontent.com/1361962/130641160-1ddee199-67db-483e-adf6-d235ac95766b.png)

Permissions
![image](https://user-images.githubusercontent.com/1361962/130641244-3ab0fa75-c182-43ab-9bbf-293f55d06965.png)

Mounts
![image](https://user-images.githubusercontent.com/1361962/130641310-3d03ea8f-7d62-4dce-a93f-cc80a5409306.png)

Logs (actual domain changed to fubar.com. Can provide actual in non-public way. Also seen above. )

> ,
0 entries in whoisdata,
Error: No match for "fubar.com" in the registrar database.
,
,
    at /app/lib/whois-manager.js:204:14,
    at new Promise (<anonymous>),
    at writeWhoisData (/app/lib/whois-manager.js:200:10),
WHOIS: Cached entries: ,,
d,
    at /app/lib/whois-manager.js:186:14,
    at async Promise.all (index 0),
::ffff:192.168.1.237 - WS client W2_34LFqTBmzd8ByAAAF | disconnection (ping timeout),
::ffff:192.168.1.237 - WS client 0OkViV3xJAC_UVJIAAAG | connection,
::ffff:192.168.1.237 - WS client 0OkViV3xJAC_UVJIAAAG | sent config,
::ffff:192.168.1.237 - WS client 0OkViV3xJAC_UVJIAAAG | sent domains,
::ffff:192.168.1.237 - WS client 0OkViV3xJAC_UVJIAAAG | No cached WHOIS for fubar.com,
::ffff:192.168.1.237 - GET / HTTP/1.1 304 - - 1.093 ms,
::ffff:192.168.1.237 - WS client 0OkViV3xJAC_UVJIAAAG | disconnection (transport close),
::ffff:192.168.1.237 - GET /js/main.js HTTP/1.1 304 - - 0.731 ms,
::ffff:192.168.1.237 - WS client EAo6i3r5Ozd3j2h1AAAH | connection,
::ffff:192.168.1.237 - WS client EAo6i3r5Ozd3j2h1AAAH | sent config,
::ffff:192.168.1.237 - WS client EAo6i3r5Ozd3j2h1AAAH | sent domains,
::ffff:192.168.1.237 - WS client EAo6i3r5Ozd3j2h1AAAH | No cached WHOIS for fubar.com,
::ffff:192.168.1.237 - GET /favicon-32x32.png HTTP/1.1 200 1181 - 1.025 ms,
creating whois promise for fubar.com,
WHOIS: No existing whois.yaml for fubar.com. Fetching..,
string received. No match for "fubar.com" in the registrar database.
,
,
0 entries in whoisdata,
Error: No match for "fubar.com" in the registrar database.
,
,
    at /app/lib/whois-manager.js:204:14,
    at new Promise (<anonymous>),
    at writeWhoisData (/app/lib/whois-manager.js:200:10),
    at /app/lib/whois-manager.js:186:14,
    at async Promise.all (index 0),
WHOIS: Cached entries: ,,
d,
::ffff:192.168.1.237 - WS client EAo6i3r5Ozd3j2h1AAAH | disconnection (ping timeout),
::ffff:192.168.1.237 - WS client u2XdxOJJzfvXB_yUAAAI | connection,
::ffff:192.168.1.237 - WS client u2XdxOJJzfvXB_yUAAAI | sent config,
::ffff:192.168.1.237 - WS client u2XdxOJJzfvXB_yUAAAI | sent domains,
::ffff:192.168.1.237 - WS client u2XdxOJJzfvXB_yUAAAI | No cached WHOIS for fubar.com,
creating whois promise for fubar.com,
WHOIS: No existing whois.yaml for fubar.com. Fetching..,
string received. No match for "fubar.com" in the registrar database.
,
,
0 entries in whoisdata,
Error: No match for "fubar.com" in the registrar database.
,
,
    at /app/lib/whois-manager.js:204:14,
    at new Promise (<anonymous>),
    at writeWhoisData (/app/lib/whois-manager.js:200:10),
    at /app/lib/whois-manager.js:186:14,
    at async Promise.all (index 0),
WHOIS: Cached entries: ,,
d,
::ffff:192.168.1.237 - WS client u2XdxOJJzfvXB_yUAAAI | disconnection (transport close),
creating whois promise for fubar.com,
WHOIS: No existing whois.yaml for fubar.com. Fetching..,
string received. No match for "fubar.com" in the registrar database.
,
,
0 entries in whoisdata,
WHOIS: Cached entries: ,
Error: No match for "fubar.com" in the registrar database.
,
,
    at /app/lib/whois-manager.js:204:14,
    at new Promise (<anonymous>),
    at writeWhoisData (/app/lib/whois-manager.js:200:10),
    at /app/lib/whois-manager.js:186:14,
    at async Promise.all (index 0),,
d,
creating whois promise for fubar.com,
WHOIS: No existing whois.yaml for fubar.com. Fetching..,
string received. No match for "fubar.com" in the registrar database.
,
,
0 entries in whoisdata,
Error: No match for "fubar.com" in the registrar database.
,
,
    at /app/lib/whois-manager.js:204:14,
    at new Promise (<anonymous>),
    at writeWhoisData (/app/lib/whois-manager.js:200:10),
    at /app/lib/whois-manager.js:186:14,
    at async Promise.all (index 0),
WHOIS: Cached entries: ,,
d,
creating whois promise for fubar.com,
WHOIS: No existing whois.yaml for fubar.com. Fetching..,
string received. No match for "fubar.com" in the registrar database.
,
,
0 entries in whoisdata,
Error: No match for "fubar.com" in the registrar database.
,
,
    at /app/lib/whois-manager.js:204:14,
    at new Promise (<anonymous>),
    at writeWhoisData (/app/lib/whois-manager.js:200:10),
    at /app/lib/whois-manager.js:186:14,
    at async Promise.all (index 0),
WHOIS: Cached entries: ,,
d

**Comment by nwesterhausen** [comment]
Updated docker images :latest and tagged specifically :0.3.3

Please try with the changes and let me know how it goes.

**Comment by sugarfunk** [comment]
same results. added 2nd domain just in case.

> Serving static site from /app/client,
Web interface available at http://localhost:4201/,
::ffff:192.168.1.237 - WS client P1eXH1YWxyPbPdOaAAAA | connection,
::ffff:192.168.1.237 - WS client P1eXH1YWxyPbPdOaAAAA | sent config,
::ffff:192.168.1.237 - WS client P1eXH1YWxyPbPdOaAAAA | sent domains,
::ffff:192.168.1.237 - WS client P1eXH1YWxyPbPdOaAAAA | No cached WHOIS for bartdyer.com,
creating whois promise for bartdyer.com,
WHOIS: No existing whois.yaml for bartdyer.com. Fetching..,
string received. No match for "bartdyer.com" in the registrar database.
,
,
0 entries in whoisdata,
Parsing seems to have failed, writing dump.,
Error: No match for "bartdyer.com" in the registrar database.,
,
    at /app/lib/whois-manager.js:204:14,
    at new Promise (<anonymous>),
WHOIS: Cached entries: ,,
d,
    at writeWhoisData (/app/lib/whois-manager.js:200:10),
    at /app/lib/whois-manager.js:186:14,
    at async Promise.all (index 0),
::ffff:192.168.1.82 - GET / HTTP/1.1 200 10506 - 8.170 ms,
::ffff:192.168.1.82 - GET /js/main.js HTTP/1.1 200 11835 - 1.994 ms,
::ffff:192.168.1.82 - WS client j78Is9cKqsSF9h03AAAB | connection,
::ffff:192.168.1.82 - WS client j78Is9cKqsSF9h03AAAB | sent domains,
::ffff:192.168.1.82 - WS client j78Is9cKqsSF9h03AAAB | sent config,
::ffff:192.168.1.82 - WS client j78Is9cKqsSF9h03AAAB | No cached WHOIS for bartdyer.com,
::ffff:192.168.1.82 - GET /favicon-32x32.png HTTP/1.1 200 1181 - 1.248 ms,
::ffff:192.168.1.82 - GET /favicon-32x32.png HTTP/1.1 304 - - 1.124 ms,
::ffff:192.168.1.82 - WS client j78Is9cKqsSF9h03AAAB | SCK_UPDATE_DOMAIN: {"name":"F3 Nation","fqdn":"f3nation.com","alerts":true,"enabled":true},
::ffff:192.168.1.82 - WS client j78Is9cKqsSF9h03AAAB | sent domain update.,
::ffff:192.168.1.82 - WS client j78Is9cKqsSF9h03AAAB | No cached WHOIS for bartdyer.com,
::ffff:192.168.1.82 - WS client j78Is9cKqsSF9h03AAAB | No cached WHOIS for f3nation.com,
::ffff:192.168.1.82 - GET / HTTP/1.1 304 - - 0.592 ms,
::ffff:192.168.1.82 - WS client j78Is9cKqsSF9h03AAAB | disconnection (transport close),
::ffff:192.168.1.82 - GET /js/main.js HTTP/1.1 304 - - 0.561 ms,
::ffff:192.168.1.82 - WS client BjMW1S_uwvYwmKffAAAC | connection,
::ffff:192.168.1.82 - WS client BjMW1S_uwvYwmKffAAAC | sent config,
::ffff:192.168.1.82 - WS client BjMW1S_uwvYwmKffAAAC | sent domains,
::ffff:192.168.1.82 - WS client BjMW1S_uwvYwmKffAAAC | No cached WHOIS for bartdyer.com,
::ffff:192.168.1.82 - WS client BjMW1S_uwvYwmKffAAAC | No cached WHOIS for f3nation.com,
::ffff:192.168.1.82 - GET /favicon-32x32.png HTTP/1.1 200 1181 - 1.111 ms,
::ffff:192.168.1.82 - GET / HTTP/1.1 200 10506 - 2.149 ms,
::ffff:192.168.1.82 - WS client BjMW1S_uwvYwmKffAAAC | disconnection (transport close),
::ffff:192.168.1.82 - GET /js/main.js HTTP/1.1 200 11835 - 0.758 ms,
::ffff:192.168.1.82 - WS client J-4xGWBzXK-uVqnXAAAD | connection,
::ffff:192.168.1.82 - WS client J-4xGWBzXK-uVqnXAAAD | sent config,
::ffff:192.168.1.82 - WS client J-4xGWBzXK-uVqnXAAAD | sent domains,
::ffff:192.168.1.82 - WS client J-4xGWBzXK-uVqnXAAAD | No cached WHOIS for bartdyer.com,
::ffff:192.168.1.82 - WS client J-4xGWBzXK-uVqnXAAAD | No cached WHOIS for f3nation.com,
::ffff:192.168.1.82 - GET /favicon-32x32.png HTTP/1.1 200 1181 - 1.105 ms

**Comment by nwesterhausen** [comment]
I'm testing again. When I did previous did so literally for fubar.com and since I had it produce the error then resolve I thought I got it. When I with my test conditions defined below, I only get an error for one of your domains and it's because the registrar said it had no data (basically replied with that string and it isn't WHOIS data). `No match for bar********.com in the registrar database.`

I will improve the handling for this error. I didn't have any issues with the other domain you used in my test scenario.

docker-compose.yml:

```yaml
services:
  dm:
    image: ghcr.io/nwesterhausen/domain-monitor/server:latest
    ports:
    - 127.0.0.1:4201:4201/tcp
    volumes:
    - /home/nwest/dm-test/config:/app/config:rw
    - /home/nwest/dm-test/whois:/app/whois-data:rw
version: '3.9'
```

and in `./config/domain.yaml` (redacted):

```yaml
domains:
  - name: Test
    fqdn: fubar.com
    alerts: true
    enabled: true
  - name: Test2
    fqdn: bar********.com
    alerts: true
    enabled: true
  - name: Test3
    fqdn: f3n********.com
    alerts: true
    enabled: true
```

Resulting logs (previously ran with just fubar.com and had a cached entry for it):
```
Attaching to dm-test_dm_1
dm_1  | Serving static site from /app/client
dm_1  | Web interface available at http://localhost:4201/
dm_1  | creating whois promise for fubar.com
dm_1  | WHOIS: Validating cached whois data for fubar.com
dm_1  | creating whois promise for bar********.com
dm_1  | WHOIS: No existing whois.yaml for bar********.com. Fetching..
dm_1  | creating whois promise for f3n********.com
dm_1  | WHOIS: No existing whois.yaml for f3n********.com. Fetching..
dm_1  | WHOIS: Age of existing whois.yaml is 00:00:07:27 (447331)
dm_1  | WHOIS: fubar.com expires in 58:08:05:55 on Fri Oct 22 2021
dm_1  | WHOIS: Within age boundary checks for fubar.com whois.yaml
dm_1  | string received. No match for "bar********.com" in the registrar database.
dm_1  |
dm_1  | 0 entries in whoisdata
dm_1  | Parsing seems to have failed, writing dump.
dm_1  | Error: No match for "bar********.com" in the registrar database.
dm_1  |
dm_1  |     at /app/lib/whois-manager.js:204:14
dm_1  |     at new Promise (<anonymous>)
dm_1  |     at writeWhoisData (/app/lib/whois-manager.js:200:10)
dm_1  |     at /app/lib/whois-manager.js:186:14
dm_1  |     at async Promise.all (index 1)
dm_1  | string received. Domain Name: f3n********.COM
dm_1  | Registry Domain ID: 1674397384_DOMAIN_COM-VRSN
dm_1  | Registrar WHOIS Server: whois.cloudflare.com
dm_1  | Registrar URL: https://www.cloudflare.com
dm_1  | Updated Date: 2021-02-05T12:25:32Z
dm_1  | Creation Date: 2011-08-29T17:35:56Z
dm_1  | Registrar Registration Expiration Date: 2021-09-24T11:59:59Z
dm_1  | Registrar: Cloudflare, Inc.
dm_1  | Registrar IANA ID: 1910
dm_1  | Domain Status: clienttransferprohibited https://icann.org/epp#clienttransferprohibited
dm_1  | Registry Registrant ID:
dm_1  | Registrant Name: DATA REDACTED
dm_1  | Registrant Organization: DATA REDACTED
dm_1  | Registrant Street: DATA REDACTED
dm_1  | Registrant City: DATA REDACTED
dm_1  | Registrant State/Province: NC
dm_1  | Registrant Postal Code: DATA REDACTED
dm_1  | Registrant Country: US
dm_1  | Registrant Phone: DATA REDACTED
dm_1  | Registrant Phone Ext: DATA REDACTED
dm_1  | Registrant Fax: DATA REDACTED
dm_1  | Registrant Fax Ext: DATA REDACTED
dm_1  | Registrant Email: https://domaincontact.cloudflareregistrar.com/f3n********.com
dm_1  | Registry Admin ID:
dm_1  | Admin Name: DATA REDACTED
dm_1  | Admin Organization: DATA REDACTED
dm_1  | Admin Street: DATA REDACTED
dm_1  | Admin City: DATA REDACTED
dm_1  | Admin State/Province: DATA REDACTED
dm_1  | Admin Postal Code: DATA REDACTED
dm_1  | Admin Country: DATA REDACTED
dm_1  | Admin Phone: DATA REDACTED
dm_1  | Admin Phone Ext: DATA REDACTED
dm_1  | Admin Fax: DATA REDACTED
dm_1  | Admin Fax Ext: DATA REDACTED
dm_1  | Admin Email: https://domaincontact.cloudflareregistrar.com/f3n********.com
dm_1  | Registry Tech ID:
dm_1  | Tech Name: DATA REDACTED
dm_1  | Tech Organization: DATA REDACTED
dm_1  | Tech Street: DATA REDACTED
dm_1  | Tech City: DATA REDACTED
dm_1  | Tech State/Province: DATA REDACTED
dm_1  | Tech Postal Code: DATA REDACTED
dm_1  | Tech Country: DATA REDACTED
dm_1  | Tech Phone: DATA REDACTED
dm_1  | Tech Phone Ext: DATA REDACTED
dm_1  | Tech Fax: DATA REDACTED
dm_1  | Tech Fax Ext: DATA REDACTED
dm_1  | Tech Email: https://domaincontact.cloudflareregistrar.com/f3n********.com
dm_1  | Registry Billing ID:
dm_1  | Billing Name: DATA REDACTED
dm_1  | Billing Organization: DATA REDACTED
dm_1  | Billing Street: DATA REDACTED
dm_1  | Billing City: DATA REDACTED
dm_1  | Billing State/Province: DATA REDACTED
dm_1  | Billing Postal Code: DATA REDACTED
dm_1  | Billing Country: DATA REDACTED
dm_1  | Billing Phone: DATA REDACTED
dm_1  | Billing Phone Ext: DATA REDACTED
dm_1  | Billing Fax: DATA REDACTED
dm_1  | Billing Fax Ext: DATA REDACTED
dm_1  | Billing Email: https://domaincontact.cloudflareregistrar.com/f3n********.com
dm_1  | Name Server: gabe.ns.cloudflare.com
dm_1  | Name Server: paris.ns.cloudflare.com
dm_1  | DNSSEC: unsigned
dm_1  | Registrar Abuse Contact Email: registrar-abuse@cloudflare.com
dm_1  | Registrar Abuse Contact Phone: +1.4153197517
dm_1  | URL of the ICANN WHOIS Data Problem Reporting System: http://wdprs.internic.net/
dm_1  | >>> Last update of WHOIS database: 2021-08-25T14:54:04Z <<<
dm_1  |
dm_1  | For more information on Whois status codes, please visit https://icann.org/epp
dm_1  |
dm_1  | Cloudflare provides more than 13 million domains with the tools to give their global users a faster, more secure, and more reliable internet experience.
dm_1  |
dm_1  | NOTICE:
dm_1  |
dm_1  | Data in the Cloudflare Registrar WHOIS database is provided to you by Cloudflare
dm_1  | under the terms and conditions at https://www.cloudflare.com/domain-registration-agreement/
dm_1  |
dm_1  | By submitting this query, you agree to abide by these terms.
dm_1  |
dm_1  | Register your domain name at https://www.cloudflare.com/registrar/
dm_1  |
dm_1  | Key found before newline, attempting to elaborate whois data.
dm_1  | 65 entries in whoisdata
dm_1  | WHOIS: Cached entries:
dm_1  | [ 'fubar.com', true ]
dm_1  | undefined
dm_1  | undefined
dm_1  | ::ffff:10.210.6.1 - GET / HTTP/1.1 200 10506 - 13.691 ms
dm_1  | ::ffff:10.210.6.1 - GET /js/main.js HTTP/1.1 200 11835 - 2.404 ms
dm_1  | ::ffff:10.210.6.1 - WS client G-rEEJD5efrslHWQAAAA | connection
dm_1  | ::ffff:10.210.6.1 - WS client G-rEEJD5efrslHWQAAAA | sent config
dm_1  | ::ffff:10.210.6.1 - WS client G-rEEJD5efrslHWQAAAA | sent domains
dm_1  | ::ffff:10.210.6.1 - WS client G-rEEJD5efrslHWQAAAA | No cached WHOIS for bar********.com
dm_1  | ::ffff:10.210.6.1 - WS client G-rEEJD5efrslHWQAAAA | Sent WHOIS for f3n********.com
dm_1  | ::ffff:10.210.6.1 - WS client G-rEEJD5efrslHWQAAAA | Sent WHOIS for fubar.com
dm_1  | ::ffff:10.210.6.1 - GET /favicon-32x32.png HTTP/1.1 200 1181 - 1.735 ms
dm_1  | ::ffff:10.210.6.1 - GET /site.webmanifest HTTP/1.1 200 263 - 1.734 ms
```

**Comment by nwesterhausen** [comment]
Currently on the develop image it will handle the "No match" response from the whois lookup more gracefully. Working on having it give feedback client-side but have to figure out how to handle that.

Logs from running after change:
```
Attaching to dm-test_dm_1
dm_1  | domain-monitor v0.3.3-develop
dm_1  | Serving static site from /app/client
dm_1  | Web interface available at http://localhost:4201/
dm_1  | creating whois promise for fubar.com
dm_1  | WHOIS: Validating cached whois data for fubar.com
dm_1  | creating whois promise for bar********.com
dm_1  | WHOIS: No existing whois.yaml for bar********.com. Fetching..
dm_1  | creating whois promise for f3n********.com
dm_1  | WHOIS: Validating cached whois data for f3n********.com
dm_1  | WHOIS: Age of existing whois.yaml is 00:00:55:47 (3347774)
dm_1  | WHOIS: fubar.com expires in 58:07:17:35 on Fri Oct 22 2021
dm_1  | WHOIS: Within age boundary checks for fubar.com whois.yaml
dm_1  | WHOIS: Age of existing whois.yaml is 00:00:48:20 (2900783)
dm_1  | WHOIS: f3n********.com expires in 29:20:17:34 on Fri Sep 24 2021
dm_1  | WHOIS: Within age boundary checks for f3n********.com whois.yaml
dm_1  | WHOIS Request for bar********.com returned no match!
dm_1  | -- BEGIN WHOIS RESPONSE --
dm_1  | No match for "bar********.com" in the registrar database.
dm_1  |
dm_1  | -- END WHOIS RESPONSE --
dm_1  | Skipping writing to cache, will try again soon.
dm_1  | WHOIS: Cached entries:
dm_1  | [ 'fubar.com', true ]
dm_1  | undefined
dm_1  | [ 'f3n********.com', true ]
```

**Comment by nwesterhausen** [comment]
I haven't been able to duplicate messed up WHOIS queries since switching to `golang` for the project. Please open a new issue if lookups are failing / cache breaking
