### ISSUE TITLE
Test alerts from Web UI

### ISSUE THREAD

**Issue by SkipTheDragon** [nwesterhausen/domain-monitor#49]
There is no way for me to check if the alerts will work if needed, It would be really useful and assuring if we had a way to verify the SMTP connection by sending a test email from the Web UI.

Most apps have this feature these days, like NextCloud, ValutWarden etc.

How does this sound ?

**Comment by jorbig** [comment]
I second this request. Or is there any workaround?

**Comment by nwesterhausen** [comment]
This will be possible in the next update, which is coming along nicely.

**Comment by nwesterhausen** [comment]
This is in version 1.0.0
