### ISSUE TITLE
Support for ARM64

### ISSUE THREAD

**Issue by lindermayr** [nwesterhausen/domain-monitor#66]
Most of my Docker containers run on Raspberry Pi or in a free instance of Oracle Cloud. Unfortunately, they only support ARM64, so your software always exits with this error: exec /usr/local/bin/docker-entrypoint.sh: exec format error.

I've found some instructions for adding multiple platform support:
https://docs.docker.com/build/building/multi-platform/

Do you think it'd be possible to tweak your software to play nice with different architectures like ARM64? That'd be a huge help!

**Comment by nwesterhausen** [comment]
Sounds like a good idea to add!

**Comment by nwesterhausen** [comment]
ARM64 build will be automatic from 1.2.4 (current latest) onward.
